server:
    port: 8762
    
#eureka配置
eureka:
    instance:
        hostname: eurekaServer8762   #集群版写法
    client:
        register-with-eureka: false   #是否将自己注册到eureka 服务当中（默认true）.
        fetch-registry: false         #是否启用从注册中心拉取服务列表的功能（默认true）.
        service-url:
            #这是集群版写法，13000注册给8762；反之，8762要注册给13000.
            defaultZone: http://localhost:8761/eureka/
    server:
        enable-self-preservation: false     #关闭自我保护机制

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/elm?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver