server:
    port: 15000

spring:    
    application:
        name: config-server
    cloud:
        config:            #有关springcloud config的配置          
            server:
                git:
                    default-label: main
                    uri: https://github.com/18zzero/elm.git  #git远程仓库地址
    datasource:
        url: jdbc:mysql://localhost:3306/elm?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
#eureka配置
eureka:
    client:
        service-url:
            #将自己注册给defaultZone所指定的eureka server集群上
            defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    instance:        
        prefer-ip-address: true   #使用ip地址向eureka server进行注册
        instance-id: ${spring.cloud.client.ip-address}:${server.port}   #设置eureka控制台中显示的注册信息   
        lease-renewal-interval-in-seconds: 5         #续约间隔时间
        lease-expiration-duration-in-seconds: 15     #续约到期时间       