server:
    port: 14000
    
spring:    
    application:
        name: gateway-server
    main:
        web-application-type: reactive
    datasource:
        url: jdbc:mysql://localhost:3306/elm?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
    #下面是关于Gateway的配置
    cloud:    
        gateway:
            globalcors:           #设置全局跨域处理
                corsConfigurations:
                    '[/**]':
                        allowedOrigins: "*"
                        allowedHeaders: "*"
                        allowedMethods: 
                        -   GET
                        -   POST
                        -   PUT
                        -   DELETE

            routes:               #设置路由
            -   id: userServer
                uri: lb://user-server
                predicates:
                -   Path=/UserController/*/**
                
            -   id: foodServer
                uri: lb://food-server
                predicates:
                -   Path=/FoodController/*/**
                
            -   id: businessServer
                uri: lb://business-server
                predicates:
                -   Path=/BusinessController/*/**
                
            -   id: cartServer
                uri: lb://cart-server
                predicates:
                -   Path=/CartController/*/**
                
            -   id: deliveryaddressServer
                uri: lb://deliveryaddress-server
                predicates:
                -   Path=/DeliveryAddressController/*/**
                
            -   id: ordersServer
                uri: lb://orders-server
                predicates:
                -   Path=/OrdersController/*/**       
                
#eureka配置
eureka:        
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    instance:        
        prefer-ip-address: true   #使用ip地址向eureka server进行注册
        instance-id: ${spring.cloud.client.ip-address}:${server.port}  
        lease-renewal-interval-in-seconds: 5         #续约间隔时间
        lease-expiration-duration-in-seconds: 15     #续约到期时间